### ISSUE TITLE
i get api error even when i put in the correct api info 

### ISSUE THREAD

**Issue by Digiguy1** [kirkins/miniMarketMaker#7]
×
Error: You need to pass an API key and secret to make authenticated calls.
▶ 3 stack frames were collapsed.
SwingTrade.makeTrade
src/modules/SwingTrade.js:115
  112 | let price = this.state.buy ? this.state.buyPrice : this.state.sellPrice
  113 | let messageText = side + " " + this.state.quantity + " " + this.state.selectedPair + " for " + price
  114 | message.info(messageText)
> 115 | binance.order({
  116 |   symbol: this.state.selectedPair,
  117 |   side: side,
  118 |   quantity: this.state.quantity,

please help i would love to get this app up and running

**Comment by kirkins** [comment]
I think there was an error when saving settings for the first time. I made a [small update](https://github.com/kirkins/miniMarketMaker/commit/42313c0851007fbc6a6a93a63ed6ab4b1b31d2ff).

Can you try again?

**Comment by Digiguy1** [comment]
thanks
